

INSERT INTO restaurant (name, phone_number, address)
VALUES ('The Bestaurant',
        '727-555-5555',
        '123 Main St Dunedin, FL 34698');

INSERT INTO users (username, password)
VALUES ('testread',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q'),
       ('testhide',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q'),
       ('testedit',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q'),
       ('testdelete',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q'),
       ('testadmin',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q');

INSERT INTO menu_items (loc_id, rest_id, item_name, item_desc, price)
VALUES ('menu-lunch-dinner-appetizer-1',
        1,
        'French Fries',
        'Delicious sliced potatoes fried and seasoned',
        4.99),
        ('menu-lunch-dinner-appetizer-2',
         1,
         'Garlic Bread',
         'Fresh made bread baked and covered with cheese and garlic',
         5.99),
        ('menu-lunch-dinner-appetizer-3',
         1,
         'Deviled Eggs',
         'Two halved eggs filled with our in house mixture',
         6.99),
        ('menu-lunch-appetizer-4',
         1,
         'Home Fries',
         'Diced potatoes fried and seasoning with in house flavors',
         4.99),
        ('menu-lunch-dinner-appetizer-5',
         1,
         'Brussel Sprouts',
         'Crispy brussel sprouts with some gorgonzola cheese',
         6.99),
        ('menu-dinner-appetizer-6',
         1,
         'Breaded Chicken Bites',
         'Lightly breaded, bite sized fried chicken breast',
         5.99),
        ('menu-dinner-appetizer-7',
         1,
         'House Salad',
         'Typical garden salad served with our in house ranch',
         5.99),
        ('menu-dinner-appetizer-8',
         1,
         'Mussels',
         'Small portion of steamed mussels in a white wine sauce',
         9.99),
        ('menu-lunch-sandwiches-1',
         1,
         'Grilled Cheese',
         'A grilled cheese server with white cheddar, tomato, arugala and avocado',
         11.99),
        ('menu-lunch-sandwhiches-2',
         1,
         'Breakfast Sandwhich',
         'Served on a croissant with ham, a fried egg and cheese',
         12.99),
        ('menu-lunch-sandwhiches-3',
         1,
         'French Toast Sammy',
         'Served on two piece of french toast, maple glaze, sausage and egg',
         14.99),
        ('menu-dinner-sandwhiches-4',
         1,
         'American Burger',
         'A 6oz patty served on a brioche bun with tomat, onion and lettuce',
         13.99),
        ('menu-dinner-sandwhiches-5',
         1,
         'Grilled Chicken Sandwhich',
         'A grilled chicken breast served on wheat bread with tomato, lettuce and choice of sauce',
         12.99),
        ('menu-dinner-sandwhiches-6',
         1,
         'Pulled Pork Sliders',
         '3 sliders with pulled pork, St Louis BBQ and house made coleslaw',
         11.99),
        ('menu-lunch-dinner-entrees-1',
         1,
         'Ribeye',
         '8oz ribeye served with mashed potatoes and broccolini',
         24.99),
        ('menu-lunch-dinner-entrees-2',
         1,
         'Seared Salmon',
         'Pan seared salmon served with basmati rice, charred peppers and a side of lemon',
         18.99),
        ('menu-lunch-dinner-entrees-3',
         1,
         'Chargrilled Wings',
         '12 wings served with celery, ranch or blue cheese, and flavored with your choice of sauce or seasoning',
         17.99),
        ('menu-lunch-dinner-entrees-4',
         1,
         'Pasta Bolognese',
         'Served with a house made meat sauce made from beef tenderloin and herbed ricotta',
         19.99),
        ('menu-lunch-dinner-sides-1',
         1,
         'Broccoli',
         'Steamed Broccoli',
         3.99),
        ('menu-lunch-dinner-sides-2',
         1,
         'Mac N Cheese',
         'Cheddar cheese noodles',
         4.99),
        ('menu-lunch-dinner-sides-3',
         1,
         'Baked Beans',
         'American baked beans in a brown sugar sauce',
         4.99),
        ('menu-lunch-dinner-sides-4',
         1,
         'Mashed Potatoes',
         'Red mashed potatoes',
         3.99),
        ('menu-lunch-dinner-sides-5',
         1,
         'Grilled Bread',
         '3 pieces of grilled bread',
         1.99),
        ('menu-drinks-cocktails-1',
         1,
         'Espresso Martini',
         'Made with real espresso and vanilla vodka',
         10.99),
        ('menu-drinks-cocktails-2',
         1,
         'Blackberry Paloma',
         'A traditional paloma with an added flavor of blackberry and mint',
         8.99),
        ('menu-drinks-cocktails-3',
         1,
         'Gin and Juice',
         'A refreshing gin, lemon and grapefruit drink',
         8.99),
        ('menu-drinks-cocktails-4',
         1,
         'Whiskey Sour',
         'Your choice of select whiskey and our bartenders skills',
         7.99),
        ('menu-drinks-cocktails-5',
         1,
         'Old Fashioned',
         'Russels 10yr bourbon flavored with bitters and a hint of sweetness',
         11.99),
        ('menu-drinks-wine-1',
         1,
         'Pinot Grigio',
         NULL,
         7.99),
        ('menu-drinks-wine-2',
         1,
         'Sauvignon Blanc',
         NULL,
         7.99),
        ('menu-drinks-wine-3',
         1,
         'Cabernet',
         NULL,
         9.99),
        ('menu-drinks-wine-4',
         1,
         'Chardonnay',
         NULL,
         9.99),
        ('menu-drinks-beer-1',
         1,
         'Bud Light',
         NULL,
         4.99),
        ('menu-drinks-beer-2',
         1,
         'Corona',
         NULL,
         5.99),
        ('menu-drinks-beer-3',
         1,
         'Miller Lite',
         NULL,
         4.99),
        ('menu-drinks-beer-4',
         1,
         'Budweiser',
         NULL,
         4.99);

INSERT INTO hours (rest_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday)
VALUES (1,
        '10am - 10pm',
        'Closed',
        '10am - 10pm',
        '10am - 10pm',
        '10am - 12am',
        '9am - 12am',
        '9am - 10pm');

INSERT INTO permissions (user_id, rest_id, admin_privileges)
VALUES (1, 1, 'read'),
       (2, 1, 'hide'),
       (3, 1, 'edit'),
       (4, 1, 'delete');

INSERT INTO text_content (loc_id, rest_id, content)
VALUES ('home-s1', 1, 'The Bestaurant has been established in Dunedin for the last 20 years and has continued to thrive thanks to our mission to satisfy every customer and our loyal and fanatical customers. Welcome to the Bestaurant, where the best is what you want.'),
       ('home-h1', 1, 'Your next great experience awaits'),
       ('home-h2', 1, 'Great people, even better food'),
       ('home-s2', 1, 'Our mission for the best doesnt stop at our ingredients but in our employees too. With our award winning chefs and expert bartenders you are sure to love every bite, sip and taste!'),
       ('home-h3', 1, 'Catering, Careers and More!'),
       ('home-s3', 1, 'Want to be apart of our team or just looking for the food for your next party? Get in touch with us here!');